Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.define "backport-gutenprint"
  config.vm.synced_folder ".", "/vagrant", type: "sshfs"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.vm.provision "shell", path: "provision.sh"
end
